spring.application.name=Auroneqis

server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/auroneqis_db
spring.datasource.username=root
spring.datasource.password=Hyndhavi@2405

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=auronequispvtltd@gmail.com
spring.mail.password=pwyj hwrc pyzd nhxv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.admin=info@auroneqis.com

app.upload.blog-images-path=/root/uploads/blog-images

app.cors.allowed-origins=https://auroneqis.com,https://www.auroneqis.com
